services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      - DATABASE_URL

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL
      - BETTER_AUTH_SECRET
      - BETTER_AUTH_URL
      - APP_URL
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
    depends_on:
      migrate:
        condition: service_completed_successfully
