services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    restart: "no"
    environment:
      - DATABASE_URL=${DATABASE_URL:?}

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL:?}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:?}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL:?}
      - APP_URL=${APP_URL:?}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:?}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:?}
      - SERVICE_URL_API_3000
    depends_on:
      migrate:
        condition: service_completed_successfully
